name: opensn
description: Dart SDK for OpenSN (The Open Social Network) project for both Dart and Flutter.
version: 0.0.1
repository: https://github.com/opensn/dart_sdk
homepage: https://opensn.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.1.0
  grpc: ^3.1.0
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
